name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Setup Node.js environment
        uses: actions/setup-node@v1
        with:
          node-version: '14'

      - name: Install Gitbook CLI
        run: npm install gitbook-cli@latest -g

      - name: Install dependencies 
        run : gitbook install 

      - name : Build GitBook 
        run : gitbook build
      
      # Add any additional steps for deploying to GitHub Pages here, such as copying the generated files to a specific folder or branch.
	   - name: Deploy to Github Pages
         uses: peaceiris/actions-gh-pages@v3
         with:
           github_token: ${{ secrets.GITHUB_TOKEN }}
           publish_dir: ./_book
